### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by b9Joker108** [Ailothaen/RedditArchiver-standalone#9] opened 2024-10-17 22:51 UTC
Thanks for your code. It works. But, it doesn't work. It generates a html file of the thread, but it truncates the thread and it loses heaps of the posts. So, it isn't the solution it purports to be. I am most disappoinnted.

**Comment by Ailothaen** [comment] 2024-11-13 16:59
Hello! Sorry for not responding earlier, this issue went over my head.

Normally, the tool takes care of retrieving every comment in a submission. Could you tell what was lost, and if you notice a pattern (example: nested comments lost after the nth branch, or comments lost after a certain date... ?)

If you can share it, the URL or ID of the thread would be useful for me to attempt to reproduce the issue.

**Comment by Ailothaen** [comment] 2024-12-03 21:05
I am closing this issue since there is no reply and I was not able to reproduce it.

Feel free to open another if you notice the issue again; however, please include as well examples of submissions that cause problems, as well as the logs/console output if possible.

**Closed as not planned by Ailothaen** 2024-12-03 21:05 UTC
