### ISSUE TITLE
429 HTTP response - TooManyRequests

### ISSUE THREAD

**Issue by 2600box** [Ailothaen/RedditArchiver-standalone#7] opened 2024-09-10 19:51 UTC
Hello,

This is great, though I wasted far too much time on the web version, only to release there is no bulk download capacity there!

Unfortunately, I still run into an issue trying to archive my 900 saved posted. `python3 RedditArchiver.py -s`

It seems that the API rate-limits at some point and the script dies.

Unless I am mistaken, re-running the script starts from the beginning, rather than only downloading the missing posts.

I could not see any switch to slow or limit the speed of the process either, only the total number of posts.

Perhaps I am mistaken and there is something obvious I am missing in the docs? Thanks!

```
 python3 RedditArchiver.py -h
usage: RedditArchiver.py [-i ID/URL] [-I file] [-s] [-S] [-a [name]] [-A [name]] [-u] [-l N] [-c path] [-o path] [-q] [-h]

Standalone version of RedditArchiver. Lets you download Reddit threads in a nicely readable HTML file.

Selection:
  Use at least one of these options to select what you want to save. Arguments can be used several times to specify more than one ID, URL or author.

  -i ID/URL, --id ID/URL
                        ID or URL of a submission
  -I file, --file file  same as -i, but reads IDs or URLs from a file
  -s, --saved           your saved submissions
  -S, --saved-extended  same as -s, but also saves the submissions that you saved a comment from
  -a [name], --author [name]
                        submissions posted from someone (by default: yourself)
  -A [name], --author-extended [name]
                        same as -a, but also saves the submissions where the person posted a comment in
  -u, --upvoted         submissions that you upvoted

Various:
  Other options controlling various things such as configuration, output directory...

  -l N, --limit N       limits the number of submissions retrieved with -s/-S, -a/-A and -u (newest first). Please note that the maximum is 1000 and Reddit will refuse to give anything past this limit.
  -c path, --config path
                        uses a different config file (default: ./config.yml).
  -o path, --output path
                        output directory (default: current directory)
  -q, --quiet           will not generate any message (except for errors)
  -h, --help            Show this help message and exit
```

The error that I am running into is this:

```
[x] Uncaught problem: received 429 HTTP response
Traceback (most recent call last):
  File "/Users/2600box/dev/RedditArchiver-standalone/RedditArchiver.py", line 415, in <module>
    submission, comments_index, comments_forest = download_submission(submission, submission_id)
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/2600box/dev/RedditArchiver-standalone/RedditArchiver.py", line 168, in download_submission
    submission.comments.replace_more(limit=None)
  File "/Users/2600box/.pyenv/versions/3.12.2/lib/python3.12/site-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/2600box/.pyenv/versions/3.12.2/lib/python3.12/site-packages/praw/models/comment_forest.py", line 183, in replace_more
    new_comments = item.comments(update=False)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/2600box/.pyenv/versions/3.12.2/lib/python3.12/site-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/2600box/.pyenv/versions/3.12.2/lib/python3.12/site-packages/praw/models/reddit/more.py", line 76, in comments
    self._comments = self._reddit.post(API_PATH["morechildren"], data=data)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/2600box/.pyenv/versions/3.12.2/lib/python3.12/site-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/2600box/.pyenv/versions/3.12.2/lib/python3.12/site-packages/praw/reddit.py", line 842, in post
    return self._objectify_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/2600box/.pyenv/versions/3.12.2/lib/python3.12/site-packages/praw/reddit.py", line 517, in _objectify_request
    self.request(
  File "/Users/2600box/.pyenv/versions/3.12.2/lib/python3.12/site-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/2600box/.pyenv/versions/3.12.2/lib/python3.12/site-packages/praw/reddit.py", line 941, in request
    return self._core.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/2600box/.pyenv/versions/3.12.2/lib/python3.12/site-packages/prawcore/sessions.py", line 328, in request
    return self._request_with_retries(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/2600box/.pyenv/versions/3.12.2/lib/python3.12/site-packages/prawcore/sessions.py", line 267, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.TooManyRequests: received 429 HTTP response
```

**Comment by Ailothaen** [comment] 2024-09-13 16:15
Hello,

Just to be sure, is your PRAW version up-to-date? (the latest version should be 7.7.1)

**Comment by 2600box** [comment] 2024-09-14 08:27
Thanks for the message. As the requirements.txt only calls for `praw >= 7.6.1` version 7.7.0 was installed.

I installed the latest source version of 7.7.2-DEV but it still has the same...

I also tried installing from source the prawcore with the same result.

```
[x] Uncaught problem: received 429 HTTP response
Traceback (most recent call last):
  File "/Users/2600box/dev/RedditArchiver-standalone/RedditArchiver.py", line 415, in <module>
    submission, comments_index, comments_forest = download_submission(submission, submission_id)
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/2600box/dev/RedditArchiver-standalone/RedditArchiver.py", line 168, in download_submission
    submission.comments.replace_more(limit=None)
  File "/Users/2600box/.pyenv/versions/3.12.2/lib/python3.12/site-packages/praw/util/deprecate_args.py", line 46, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/2600box/.pyenv/versions/3.12.2/lib/python3.12/site-packages/praw/models/comment_forest.py", line 192, in replace_more
    new_comments = item.comments(update=False)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/2600box/.pyenv/versions/3.12.2/lib/python3.12/site-packages/praw/util/deprecate_args.py", line 46, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/2600box/.pyenv/versions/3.12.2/lib/python3.12/site-packages/praw/models/reddit/more.py", line 79, in comments
    self._comments = self._reddit.post(API_PATH["morechildren"], data=data)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/2600box/.pyenv/versions/3.12.2/lib/python3.12/site-packages/praw/util/deprecate_args.py", line 46, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/2600box/.pyenv/versions/3.12.2/lib/python3.12/site-packages/praw/reddit.py", line 853, in post
    return self._objectify_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/2600box/.pyenv/versions/3.12.2/lib/python3.12/site-packages/praw/reddit.py", line 514, in _objectify_request
    self.request(
  File "/Users/2600box/.pyenv/versions/3.12.2/lib/python3.12/site-packages/praw/util/deprecate_args.py", line 46, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/2600box/.pyenv/versions/3.12.2/lib/python3.12/site-packages/praw/reddit.py", line 955, in request
    return self._core.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/2600box/.pyenv/versions/3.12.2/lib/python3.12/site-packages/prawcore/sessions.py", line 328, in request
    return self._request_with_retries(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/2600box/.pyenv/versions/3.12.2/lib/python3.12/site-packages/prawcore/sessions.py", line 267, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.TooManyRequests: received 429 HTTP response
```

**Comment by Ailothaen** [comment] 2024-09-23 19:17
So I had a look at this problem. From what I have seen, it looks like PRAW (the API library communicating with Reddit) relies on the `X-Ratelimit` HTTP headers, and does not try to handle HTTP 429 errors by itself when it encounters one: it raises an exception instead.

BDFR (another related project) also had similar issues, and it seems they tried to get around by using the `ratelimit_seconds` argument of PRAW: https://github.com/Serene-Arc/bulk-downloader-for-reddit/issues/910
However, after trying it myself, it does not solve the issue here.

I never came across a HTTP 429 using PRAW in normal conditions; however, I tried to run two instances of RedditArchiver at the same time, and both eventually failed in the same error.  
It is possible that RedditArchiver failed for you because the client-id is already used at the same time by another person or process: do you know if this is the case?

**Comment by Ailothaen** [comment] 2024-11-13 16:55
Closing this issue, since the problem was probably caused by using several instances of the script at the same time. This should not be done.

Feel free to open one again if the issue comes back in another condition.

**Closed as not planned by Ailothaen** 2024-11-13 16:55 UTC
